(function(){'use strict';
var V='0.2.0';
var P=[
{name:'Monday - Legs & Shoulders',ex:[['Back Squat','fixed','heavy',5,5,5,true],['Overhead Press','fixed','heavy',5,5,5,true],['Romanian Deadlift','range','medium',3,6,8,5],['Leg Curl','range','accessory',3,8,12,5],['Lateral Raise','range','accessory',3,10,15,5],['Calf Raise','range','accessory',3,10,15,5],['Front Plank','time','accessory',3,30,30,5],['Pallof Press','range','accessory',3,8,12,5]]},
{name:'Tuesday - Chest & Triceps',ex:[['Bench Press','fixed','heavy',5,5,5,true],['Incline Dumbbell Press','range','medium',3,6,10,5],['Chest Fly / Pec Deck','range','accessory',3,10,15,5],['Seated Dip Machine','range','medium',3,8,12,5],['Overhead Triceps Extension','range','accessory',3,10,15,5],['Zone 2 Cardio','time','cardio',1,1800,1800,300]]},
{name:'Wednesday - Conditioning & Mobility',ex:[['Row / Ruck / Swim','time','cardio',1,1800,1800,300],['Mobility / Pilates','time','accessory',1,900,900,300],['Grip Training','range','accessory',3,10,15,5]]},
{name:'Thursday - Back & Biceps',ex:[['Barbell Row','fixed','heavy',5,5,5,true],['Deadlift','fixed','heavy',1,5,5,true],['Lat Pulldown / Pull-up','range','medium',3,6,10,5],['Chest-Supported Row Machine','range','medium',3,8,12,5],['Face Pull','range','accessory',3,12,15,5],['EZ-Bar Curl','range','accessory',3,8,12,5],['Hammer Curl','range','accessory',2,10,15,5],['Ab Wheel Rollout','range','accessory',3,6,10,1],['Side Plank','time','accessory',2,30,30,5]]},
{name:'Friday - Functional / Athletic',ex:[['Farmer Carry','time','medium',3,40,40,5],['Sandbag Carry','time','medium',3,40,40,5],['Kettlebell Swing','range','medium',3,10,15,5],['Step-ups','range','accessory',3,8,12,5],['Intervals','time','cardio',6,30,30,0]]}
];
var C={ 'Back Squat':'Brace hard. Knees track toes. Drive through mid-foot.','Overhead Press':'Brace the trunk and press in a clean vertical path.','Romanian Deadlift':'Soft knees. Hinge back. Stop when hamstring tension limits range.','Bench Press':'Set the shoulder blades and use a consistent touch point.','Seated Dip Machine':'Keep shoulders down. Long-term goal: weighted dips.','Barbell Row':'Brace hard and pull toward the lower ribs.','Deadlift':'Brace before the pull and push the floor away.','Chest-Supported Row Machine':'Keep chest planted and squeeze the shoulder blades.','Front Plank':'Brace hard and keep hips level. Progress to harder planks over time.','Pallof Press':'Stay square and resist rotation.'};
var S={d:0,e:0,started:false,start:0,done:{},actual:{},warm:{}};var T={id:null,end:0,active:false,ready:false,audio:null};
function q(x){return document.getElementById(x)} function k(n){return'st_'+n.replace(/[^A-Za-z0-9]/g,'_')} function gw(n){var v=localStorage.getItem(k(n));return v===null?45:parseFloat(v)} function sw(n,v){localStorage.setItem(k(n),String(v))} function gn(n,d){var v=localStorage.getItem(n);return v===null?d:parseInt(v,10)} function sn(n,v){localStorage.setItem(n,String(v))} function f(s){s=Math.max(0,Math.round(s));var m=Math.floor(s/60),x=s%60;return(m<10?'0':'')+m+':'+(x<10?'0':'')+x} function rr(v){return Math.max(5,Math.round(v/5)*5)}
function exObj(a){return{name:a[0],type:a[1],kind:a[2],sets:a[3],min:a[4],max:a[5],inc:a[6]||0,warm:!!a[7],reps:a[4],seconds:a[4]}}
function rest(e){return e.kind==='heavy'?gn('st_rest_heavy',180):e.kind==='medium'?gn('st_rest_medium',120):e.kind==='cardio'?0:gn('st_rest_accessory',90)}
function warm(w){var o=[[45,5],[45,5]],a=rr(w*.5),b=rr(w*.7),c=rr(w*.85);if(w<=55)return o;if(a>45)o.push([a,5]);if(b>a)o.push([b,3]);if(c>b)o.push([c,2]);return o}
function plates(t){if(t<45)return'';var p=(t-45)/2,A=[45,35,25,10,5,2.5],u=[],i,n;for(i=0;i<A.length;i++){n=Math.floor((p+.001)/A[i]);if(n){u.push(n+'×'+A[i]);p-=n*A[i]}}return u.length?'Per side: '+u.join(' + '):'Empty bar'}
function cue(n){return C[n]||'Use controlled technique and stop if form breaks down.'}
function toast(m){var x=q('toast');x.innerHTML=m;x.style.display='block';setTimeout(function(){x.style.display='none'},1800)}
function tabs(){var B=document.querySelectorAll('nav button'),i;for(i=0;i<B.length;i++)B[i].onclick=function(){show(this.getAttribute('data-tab'))}}
function show(n){var p=document.querySelectorAll('.pane'),b=document.querySelectorAll('nav button'),i;for(i=0;i<p.length;i++)p[i].className='pane'+(p[i].id===n?' active':'');for(i=0;i<b.length;i++)b[i].className=(b[i].getAttribute('data-tab')===n?'active':'');if(n==='home')home();if(n==='train')train();if(n==='history')history();if(n==='setup')setup()}
function home(){var d=P[S.d],h=JSON.parse(localStorage.getItem('st_history')||'[]'),o='',i;for(i=0;i<P.length;i++)o+='<option value="'+i+'" '+(i===S.d?'selected':'')+'>'+P[i].name+'</option>';q('status').innerHTML='READY';q('bar').style.width='0';q('home').innerHTML='<div class="card"><div class="k">Today</div><h1>'+d.name+'</h1><p class="muted">Train with purpose. Progress with consistency.</p><div class="grid"><div class="stat">Exercises<strong>'+d.ex.length+'</strong></div><div class="stat">Default heavy rest<strong>3:00</strong></div></div><button id="start" class="primary">Start Workout</button></div><div class="card"><div class="k">Training day</div><select id="day">'+o+'</select></div><div class="card"><div class="k">Last workout</div>'+(h.length?'<b>'+h[0].day+'</b><div class="muted">'+h[0].date+'</div>':'<div class="muted">No workout saved yet.</div>')+'</div>';q('day').onchange=function(){S.d=parseInt(this.value,10);home()};q('start').onclick=function(){S.e=0;S.started=true;S.start=Date.now();S.done={};S.actual={};S.warm={};show('train')}}
function cur(){return exObj(P[S.d].ex[S.e])} function def(e){return e.type==='range'?e.max:e.type==='time'?e.seconds:e.reps}
function train(){stop(false);if(!S.started){q('train').innerHTML='<div class="card"><h1>No workout in progress</h1><button class="primary" id="go">Go Home</button></div>';q('go').onclick=function(){show('home')};return}var d=P[S.d],e=cur(),w=gw(e.name),i,h='<div class="card"><div class="k">Exercise '+(S.e+1)+' of '+d.ex.length+'</div><h1>'+e.name+'</h1><div class="cue">'+cue(e.name)+'</div>';q('status').innerHTML=(S.e+1)+' / '+d.ex.length;q('bar').style.width=((S.e/d.ex.length)*100)+'%';if(e.type==='time')h+='<div class="weight">'+f(e.seconds)+'</div>';else h+='<div class="weight">'+w+' <small>lb</small></div><div class="plates">'+plates(w)+'</div>';h+='<p>Target: '+(e.type==='range'?e.sets+' × '+e.min+'–'+e.max:e.type==='time'?e.sets+' × '+f(e.seconds):e.sets+' × '+e.reps)+'</p>';if(e.warm){var W=warm(w);if(!S.warm[S.e])S.warm[S.e]=[];h+='<div class="k">Warm-up</div>';for(i=0;i<W.length;i++)h+='<div class="row '+(S.warm[S.e][i]?'done':'')+'"><b>'+W[i][0]+' lb × '+W[i][1]+'</b><button class="tiny wb" data-i="'+i+'">'+(S.warm[S.e][i]?'Done':'Complete')+'</button></div>'}if(!S.done[S.e])S.done[S.e]=[];if(!S.actual[S.e])S.actual[S.e]=[];h+='<div class="k" style="margin-top:14px">Working sets</div>';for(i=0;i<e.sets;i++){var a=S.actual[S.e][i];if(a===undefined)a=def(e);h+='<div class="row '+(S.done[S.e][i]?'done':'')+'"><div><b>Set '+(i+1)+'</b><div class="muted">'+a+(e.type==='time'?' sec':' reps')+'</div></div><div class="actions"><button class="tiny eb" data-i="'+i+'">Edit</button><button class="tiny cb" data-i="'+i+'">'+(S.done[S.e][i]?'Done':'Complete')+'</button></div></div>'}h+='<div id="tm"></div><div class="buttons"><button id="prev" class="secondary">Previous</button><button id="next" class="primary">'+(S.e===d.ex.length-1?'Finish Workout':'Next Exercise')+'</button></div></div>';q('train').innerHTML=h;var B=document.querySelectorAll('.wb');for(i=0;i<B.length;i++)B[i].onclick=function(){var x=parseInt(this.getAttribute('data-i'),10);S.warm[S.e][x]=!S.warm[S.e][x];train()};B=document.querySelectorAll('.eb');for(i=0;i<B.length;i++)B[i].onclick=function(){var x=parseInt(this.getAttribute('data-i'),10),v=prompt('Actual '+(e.type==='time'?'seconds':'reps')+':',S.actual[S.e][x]===undefined?def(e):S.actual[S.e][x]);if(v!==null&&!isNaN(parseInt(v,10))){S.actual[S.e][x]=parseInt(v,10);train()}};B=document.querySelectorAll('.cb');for(i=0;i<B.length;i++)B[i].onclick=function(){var x=parseInt(this.getAttribute('data-i'),10);if(S.actual[S.e][x]===undefined)S.actual[S.e][x]=def(e);S.done[S.e][x]=true;train();var r=rest(e);if(r&&x<e.sets-1)startTimer(r)};q('prev').onclick=function(){if(S.e>0){S.e--;train()}};q('next').onclick=function(){if(S.e<d.ex.length-1){S.e++;train()}else finish()}}
function audio(){try{if(!T.audio){var A=window.AudioContext||window.webkitAudioContext;if(A)T.audio=new A()}if(T.audio&&T.audio.state==='suspended')T.audio.resume()}catch(e){}} function ping(){try{audio();if(T.audio){var o=T.audio.createOscillator(),g=T.audio.createGain();o.connect(g);g.connect(T.audio.destination);o.frequency.value=880;g.gain.value=.1;o.start();setTimeout(function(){o.stop()},250)}}catch(e){}try{if(navigator.vibrate)navigator.vibrate([180,100,180])}catch(e){}}
function startTimer(s){stop(false);audio();T.active=true;T.ready=false;T.end=Date.now()+s*1000;renderTimer();T.id=setInterval(function(){renderTimer();if(Math.ceil((T.end-Date.now())/1000)<=0){clearInterval(T.id);T.id=null;T.active=false;T.ready=true;ping();renderTimer()}},500)} function renderTimer(){var m=q('tm');if(!m)return;if(T.ready){m.innerHTML='<div class="timerbox"><div class="ready">READY</div><p>Rest complete</p><button id="ack" class="success">Back to Set</button></div>';q('ack').onclick=function(){T.ready=false;renderTimer()};return}if(!T.active){m.innerHTML='';return}var l=Math.max(0,Math.ceil((T.end-Date.now())/1000));m.innerHTML='<div class="timerbox"><div class="k">Rest</div><div class="timer">'+f(l)+'</div><div class="buttons"><button id="plus" class="secondary">+30 sec</button><button id="skip" class="secondary">Skip</button></div></div>';q('plus').onclick=function(){T.end+=30000};q('skip').onclick=function(){stop(true);renderTimer()}}
function stop(c){if(T.id){clearInterval(T.id);T.id=null}T.active=false;if(c)T.ready=false}
function good(e,v){var i;for(i=0;i<e.sets;i++){if(v[i]===undefined)return false;if(e.type==='fixed'&&v[i]<e.reps)return false;if(e.type==='range'&&v[i]<e.max)return false;if(e.type==='time'&&v[i]<e.seconds)return false}return true}
function finish(){stop(true);var d=P[S.d],D=[],i,e,v,ok,all=true,b;for(i=0;i<d.ex.length;i++){e=exObj(d.ex[i]);v=S.actual[i]||[];ok=good(e,v);b=gw(e.name);if((e.type==='fixed'||e.type==='range')&&ok&&e.inc)sw(e.name,b+e.inc);D.push({name:e.name,values:v,success:ok,weight:b});if(!ok)all=false}var n=prompt('Workout notes (optional):','')||'',h=JSON.parse(localStorage.getItem('st_history')||'[]');h.unshift({date:new Date().toLocaleString(),day:d.name,success:all,notes:n,details:D,duration:Math.round((Date.now()-S.start)/60000),version:V});localStorage.setItem('st_history',JSON.stringify(h.slice(0,100)));S.started=false;toast('Workout saved');show('home')}
function history(){var h=JSON.parse(localStorage.getItem('st_history')||'[]'),x='<div class="card"><h1>History</h1>',i;if(!h.length)x+='<p class="muted">No workouts saved yet.</p>';for(i=0;i<h.length;i++)x+='<div class="hist"><b>'+h[i].day+'</b><div class="muted">'+h[i].date+(h[i].duration?' • '+h[i].duration+' min':'')+'</div></div>';x+='<button id="clear" class="danger">Clear History</button></div>';q('history').innerHTML=x;q('clear').onclick=function(){if(confirm('Clear all history?')){localStorage.removeItem('st_history');history()}}}
function setup(){var seen={},x='<div class="card"><h1>Current Weights</h1><p class="muted">V1 storage keys are retained, so your current values should carry forward on the same phone/browser.</p>',i,j,e;for(i=0;i<P.length;i++)for(j=0;j<P[i].ex.length;j++){e=exObj(P[i].ex[j]);if((e.type==='fixed'||e.type==='range')&&!seen[e.name]){seen[e.name]=1;x+='<div class="field"><label>'+e.name+'</label><input class="wi" data-n="'+e.name+'" type="number" value="'+gw(e.name)+'"></div>'}}x+='<button id="savew" class="primary">Save Weights</button></div><div class="card"><h1>Rest Times</h1><div class="field"><label>Heavy compounds (seconds)</label><input id="rh" type="number" value="'+gn('st_rest_heavy',180)+'"></div><div class="field"><label>Demanding accessories (seconds)</label><input id="rm" type="number" value="'+gn('st_rest_medium',120)+'"></div><div class="field"><label>Accessories (seconds)</label><input id="ra" type="number" value="'+gn('st_rest_accessory',90)+'"></div><button id="saver" class="primary">Save Rest Times</button></div>';q('setup').innerHTML=x;q('savew').onclick=function(){var I=document.querySelectorAll('.wi'),a;for(a=0;a<I.length;a++)sw(I[a].getAttribute('data-n'),parseFloat(I[a].value||0));toast('Weights saved')};q('saver').onclick=function(){sn('st_rest_heavy',parseInt(q('rh').value||180,10));sn('st_rest_medium',parseInt(q('rm').value||120,10));sn('st_rest_accessory',parseInt(q('ra').value||90,10));toast('Rest times saved')}}
function init(){var d=new Date().getDay(),M={1:0,2:1,3:2,4:3,5:4};S.d=M[d]!==undefined?M[d]:0;tabs();home();history();setup();if('serviceWorker'in navigator)try{navigator.serviceWorker.register('sw.js')}catch(e){}}
window.onload=init;})();
